# Generated by Django 4.2.5 on 2023-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Sub_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('A', 'A'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е')], default='A', max_length=2)),
                ('first_s', models.CharField(blank=True, max_length=20)),
                ('second_s', models.CharField(blank=True, max_length=20)),
                ('third_s', models.CharField(blank=True, max_length=20)),
                ('fourth_s', models.CharField(blank=True, max_length=20)),
                ('fifth_s', models.CharField(blank=True, max_length=20)),
                ('sixth_s', models.CharField(blank=True, max_length=20)),
                ('seventh_s', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
